### ISSUE TITLE
Upgrading to new version v0.1.17 throws Failed to execute operation: require() of ES Module

### ISSUE THREAD

**Issue by adal2404-Real** [nerding-io/n8n-nodes-mcp#73]
**Upgrading to  v0.1.17 -  get errors when executing**:

Failed to execute operation: require() of ES Module /home/node/.n8n/nodes/node_modules/pkce-challenge/dist/index.node.js from /home/node/.n8n/nodes/node_modules/@modelcontextprotocol/sdk/dist/cjs/client/auth.js not supported. index.node.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules. Instead either rename index.node.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/node/.n8n/nodes/node_modules/pkce-challenge/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

**n8n version**: 1.81.4

**Comment by xerexesx** [comment]
I’m experiencing the same error. I’m using n8n version 1.85.4

**Comment by xieu90** [comment]
same here

**Comment by iamfiscus** [comment]
Is this when executing a tool specifically? Does it happen anywhere else?

**Comment by iamfiscus** [comment]
Roll back to 15 in the mean time. `n8n-nodes-mcp@0.1.15`

**Comment by iamfiscus** [comment]
I think I fixed it in `0.1.18` by overriding with `pkce-challenge: "3.0.0"` which is definitely not ideal. 

Can someone else confirm?

**Comment by xerexesx** [comment]
Still getting the same error on my side even after upgrading to 0.1.18, @iamfiscus.

**Comment by nerding-io** [comment]
Dangit. Then I'm reverting back to MCP 1.5.0 until this can get sorted out.

Would appreciate help.

**Comment by adal2404-Real** [comment]
> 0.1.18


I recently updated to version 0.1.19 and it works perfectly!

https://github.com/nerding-io/n8n-nodes-mcp/compare/v0.1.18...v0.1.19

Thanks,  @iamfiscus !
